apiVersion: v1
kind: Secret
metadata:
  name: tsa-db-secrets
type: Opaque
stringData:
  postgres-user: <replace-with-db-user>
  postgres-password: <replace-with-db-password>
  app-connection-string: Host=tsa-postgres;Port=5432;Database=tsa_submissions;Username=<replace-with-db-user>;Password=<replace-with-db-password>
